import json
import os
import warnings

from dotenv import load_dotenv  # 导入
from openai import OpenAI


# IBM WatsonX imports

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass


warnings.warn = warn
warnings.filterwarnings('ignore')

### Your Code Here:
### 1.1: Define the file_path to the text file
file_path = "California-Culinary-Map.txt"

### 1.2: Open the text file
with open(file_path, 'r', encoding='utf-8') as file:
    data = file.read()

### 1.3: Print the first 100 characters of the restaurant data
print("=== 前100个字符 ===")
print(data[:100])
print("=" * 50)

### Your Code Here:
### 2.1: Split the restaurant paragraphs into list (hint: use .split)
restaurant_list = data.split('\n\n')  # 按空行分割每家餐厅

### 2.2: Since the first item is the dataset name, we remove it
restaurant_list = restaurant_list[1:]

### 2.3: Print out the number of restaurants we have
print(f"餐厅总数：{len(restaurant_list)}")

### 2.4: Print out the first item to have a closer look at the content
print("\n=== 第一家餐厅内容 ===")
print(restaurant_list[0])
print("=" * 50)

# 自动加载 .env 文件
load_dotenv()


def llm_model(system_msg, prompt_txt):
    # 从环境变量安全读取，不会泄露
    client = OpenAI(
        api_key=os.getenv("DEEPSEEK_API_KEY"),  # 👈 安全读取
        base_url="https://api.deepseek.com"
    )

    response = client.chat.completions.create(
        model="deepseek-v4-flash",
        messages=[
            {"role": "system", "content": system_msg},
            {"role": "user", "content": prompt_txt}
        ],
        temperature=0.1,
        max_tokens=1024
    )
    return response.choices[0].message.content


import time


def safe_llm_call(system_msg, prompt_txt, retries=3):
    for i in range(retries):
        try:
            return llm_model(system_msg, prompt_txt)
        except Exception:
            time.sleep(2)
    return "Failed after retries"


# 测试 LLM
system_msg = "You are a helpful assistant."
prompt_txt = "Which place is warmer in winter? Hawaii or Greenland?"
print("LLM 测试结果：")
print(safe_llm_call(system_msg, prompt_txt))
print("=" * 50)

EXAMPLE_RESTAURANT_PARAGRAPH = restaurant_list[1]  # use the second restaurant paragraph as the example
EXAMPLE_OUTPUT = """
{
"name": "Mar de Cortez",
"location": "Santa Monica",
"type": "casual taqueria",
"food_style": "Baja-style seafood",
"rating": 4.2,
"price_range": 1,
"signatures": [
    "beer-battered snapper tacos",
    "zesty octopus ceviche"
],
"vibe": "salt-air energy",
"environment": "a premier sun-drenched spot for open-air dining near the pier.",
"shortcomings": []
}
"""


### Design your prompt here
def restaurant_data_structure_prompt_generation(restaurant_paragraph):
    base_system_msg = """
    You are a professional data extraction expert.
    You ONLY output valid JSON, no extra text.
    Extract restaurant information strictly follow the JSON schema.
    """

    base_user_prompt = f"""
    Task: Extract restaurant information into valid JSON format.
    Do NOT add any explanation, only JSON.

    Restaurant description:
    {restaurant_paragraph}

    Example Output Format:
    {EXAMPLE_OUTPUT}

    Now output JSON only:
    """
    return base_system_msg, base_user_prompt


# Unit test:
restaurant_paragraph = restaurant_list[0]
base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(
    restaurant_paragraph=restaurant_paragraph)

test_response = llm_model(system_msg=base_system_msg, prompt_txt=base_user_prompt)
print("=== 单元测试输出 ===")
print(test_response)
print("=" * 50)

# Validation
from pydantic import BaseModel, Field, ValidationError
from typing import List, Optional


### 3.1. Define the schema
class Restaurant(BaseModel):
    name: str
    location: str
    type: str
    food_style: str
    rating: Optional[float] = None
    price_range: Optional[int] = None
    signatures: List[str] = Field(default_factory=list)
    vibe: Optional[str] = None
    environment: str
    shortcomings: List[str] = Field(default_factory=list)


### 3.2. Use the validation method to validate the test_response from the unit test
try:
    restaurant_data = Restaurant.model_validate_json(test_response)
    print(f"✅ 验证成功! 餐厅名: {restaurant_data.name}")
except ValidationError as e:
    print(f"❌ 验证失败: {e.json()}")


def JSON_auto_repair_prompts(candidate_json_output, error_message):
    auto_repair_system_msg = """
    You are a JSON repair expert.
    Fix invalid JSON, output ONLY valid JSON, no extra words.
    """
    auto_repair_prompt = f"""
    Fix this JSON:
    {candidate_json_output}

    Error:
    {error_message}

    Return ONLY valid JSON:
    """
    return auto_repair_system_msg, auto_repair_prompt


### Your Code Here:
structured_restaurant_lists = []
for i, restaurant_paragraph in enumerate(restaurant_list):
    ### 2.1: Produce your initial output
    system_msg, prompt_txt = restaurant_data_structure_prompt_generation(restaurant_paragraph)
    response = safe_llm_call(system_msg, prompt_txt)

    ### 2.2: Validation and Auto Correction loop
    max_retries = 3
    current_retries = 0
    valid = False

    while not valid and current_retries < max_retries:
        try:
            Restaurant.model_validate_json(response)
            valid = True
        except ValidationError as e:
            current_retries += 1
            fix_sys, fix_prompt = JSON_auto_repair_prompts(response, str(e))
            response = safe_llm_call(fix_sys, fix_prompt)

    ### 2.3: Append your finalized response
    structured_restaurant_lists.append(response)

    # A manual progress bar
    if (i + 1) % 20 == 0:
        print(f'{i + 1} / {len(restaurant_list)} 完成')

print('✅ ALL DONE!!')

# 转 JSON 并添加 itemId
structured_restaurant_lists_json = [json.loads(response) for response in structured_restaurant_lists]

for i, item in enumerate(structured_restaurant_lists_json):
    item['itemId'] = 1000001 + i

# 保存文件
filename = 'structured_restaurant_data.json'
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(structured_restaurant_lists_json, f, indent=4, ensure_ascii=False)

print(f"\n✅ 数据已保存到: {filename}")
